version: "3.7"
volumes:
  quay-db-data:
  clair-db-data:

networks:
  quay-network:
    driver: bridge

services:
  quay-db:
    user: postgres
    container_name: quay-db
    image: docker.io/library/postgres:12.1
    environment:
      POSTGRES_USER: "quay"
      POSTGRES_PASSWORD: "quay"
      POSTGRES_DB: "quay"
    volumes:
      - "./local-dev/init/pg_bootstrap.sql:/docker-entrypoint-initdb.d/pg_bootstrap.sql"
      - "quay-db-data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - quay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quay -d quay"]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 10s

  clair-db:
    user: postgres
    container_name: clair-db
    image: docker.io/library/postgres:12.1
    command: -c 'max_connections=300'
    environment:
      POSTGRES_USER: "clair"
      POSTGRES_DB: "clair"
    volumes:
      - "clair-db-data:/var/lib/postgresql/data"
    ports:
      - "${CLAIR_DB_PORT}:5432"
    networks:
      - quay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clair -d clair"]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 10s
    cpus: 2

  redis:
    user: nobody
    container_name: quay-redis
    image: docker.io/library/redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - quay-network

  local-dev-frontend:
    user: ${DOCKER_USER:-root}
    container_name: quay-local-dev-frontend
    build:
      context: .
      target: build-static
    image: localhost/quay-build:latest
    init: true
    volumes:
      - ".:/quay-registry"
    working_dir: /quay-registry
    environment:
      npm_config_cache: /quay-registry/.npm
    networks:
      - quay-network
    entrypoint:
      - sh
      - -c
      #- npm run watch
      #- "npm install --save-dev webpack webpack-cli && npm run watch || tail -f /dev/null"
      - "npm install -g webpack@4.41.0 webpack-cli@3.3.9 && npm run watch"
    tty: true
    stdin_open: true

  quay:
    user: ${DOCKER_USER:-nobody:0}
    container_name: quay-quay
    build:
      context: .
      target: final
    image: localhost/quay-local:latest
    volumes:
      - ".:/quay-registry"
      - "./local-dev/stack:/quay-registry/conf/stack"
    ports:
      - "${QUAY_PORT}:8080"
      - "${QUAY_SSL_PORT}:8443"
    networks:
      - quay-network
    environment:
      QUAY_VERSION: local-dev
      QUAY_HOTRELOAD: "true"
      DEBUGLOG: "true"
      IGNORE_VALIDATION: "true"
      QUAYRUN: /tmp
      WORKER_COUNT_UNSUPPORTED_MINIMUM: "1"
      WORKER_COUNT: "1"
    entrypoint: ["/bin/sh", "-c"]
    command: ["tr -d '\\r' < /quay-registry/quay-entrypoint.sh > /tmp/fixed-entrypoint.sh && chmod +x /tmp/fixed-entrypoint.sh && dumb-init -- /tmp/fixed-entrypoint.sh registry"]

  clair:
    user: ${DOCKER_USER:-nobody:0}
    container_name: quay-clair
    image: quay.io/projectquay/clair:4.7.2
    volumes:
      - "./local-dev/clair:/src/clair/"
    environment:
      CLAIR_CONF: "/src/clair/config.yaml"
      CLAIR_MODE: "combo"
    # network_mode: "service:quay"  # Commented out as it's causing issues
    ports:
      - "${CLAIR_PORT}:6060"
      - "${CLAIR_API_PORT}:6061"
    networks:
      - quay-network
    cpus: 2
    command:
      ["bash", "-c", "cd /src/clair/cmd/clair; go run -mod vendor ."]